# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tmsg.proto\x12\x07protolq\"\x15\n\x04Req1\x12\r\n\x05\x64\x61ta1\x18\x01 \x01(\t\"\x16\n\x05Resp1\x12\r\n\x05\x64\x61ta1\x18\x01 \x01(\t\"$\n\x04Req2\x12\r\n\x05\x64\x61ta2\x18\x01 \x01(\r\x12\r\n\x05\x64\x61ta3\x18\x02 \x01(\x01\"\x16\n\x05Resp2\x12\r\n\x05\x64\x61ta1\x18\x01 \x01(\x01\"\x96\x01\n\tCommonMsg\x12\x1d\n\x04req1\x18\x01 \x01(\x0b\x32\r.protolq.Req1H\x00\x12\x1d\n\x04req2\x18\x02 \x01(\x0b\x32\r.protolq.Req2H\x00\x12\x1f\n\x05resp1\x18\x0b \x01(\x0b\x32\x0e.protolq.Resp1H\x00\x12\x1f\n\x05resp2\x18\x0c \x01(\x0b\x32\x0e.protolq.Resp2H\x00\x42\t\n\x07payload2@\n\x03RPC\x12\x39\n\tMsgStream\x12\x12.protolq.CommonMsg\x1a\x12.protolq.CommonMsg\"\x00(\x01\x30\x01\x42\x1fZ\x1dgithub.com/qunl/grpc1/protolqb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'msg_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\035github.com/qunl/grpc1/protolq'
  _globals['_REQ1']._serialized_start=22
  _globals['_REQ1']._serialized_end=43
  _globals['_RESP1']._serialized_start=45
  _globals['_RESP1']._serialized_end=67
  _globals['_REQ2']._serialized_start=69
  _globals['_REQ2']._serialized_end=105
  _globals['_RESP2']._serialized_start=107
  _globals['_RESP2']._serialized_end=129
  _globals['_COMMONMSG']._serialized_start=132
  _globals['_COMMONMSG']._serialized_end=282
  _globals['_RPC']._serialized_start=284
  _globals['_RPC']._serialized_end=348
# @@protoc_insertion_point(module_scope)
